import "@/app/ui/globals.css";
import { Metadata } from "next";
import Nav from "./ui/components/navigation/nav";
import Footer from "./ui/components/navigation/footer";

export const metadata: Metadata = {
  title: "The Best Online Shopping Experience",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`antialiased`}
      >
        <Nav/>
        <main className="pt-36">
          {children}
        </main>
        
        <Footer/>
      </body>
    </html>
  );
}
