import "@/app/ui/globals.css";
import { Metadata } from "next";
import Nav from "./ui/components/navigation/nav";
import Footer from "./ui/components/navigation/footer";
import StoreProvider from "./provider";

export const metadata: Metadata = {
  title: "The Best Online Shopping Experience",
  description: "Generated by create next app",
};

export default function RootLayout({children,}: Readonly<{children: React.ReactNode;}>)
{
  return (
    <html lang="en">
      <body
        className={`antialiased`}
      >
        <StoreProvider>
          <Nav/>  
          <main className="pt-36">
            {children}
          </main>
          <Footer/>
        </StoreProvider>
      </body>
    </html>
  );
}
